### ISSUE TITLE
Cant use build.sh

### ISSUE THREAD

**Issue by KOPACb** [ckeditor/ckeditor-dev#1826]
I was trying to build ckeditor from slow source to optimized using dev/build/build.sh.
I took build-config.js from site and got an error:
```java
Exception in thread "main" org.mozilla.javascript.JavaScriptException: File ../../plugins/imageuploader/lang/en.js does not exist. (C:\ckbuilder\src/lib/io.js#424)
        at ckbuilder.lib.io._c_anonymous_14(C:\ckbuilder\src/lib/io.js:424)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at ckbuilder.lib.lang._c_anonymous_6(C:\ckbuilder\src/lib/lang.js:123)
        at ckbuilder.lib.lang.call(C:\ckbuilder\src/lib/lang.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at ckbuilder.lib.lang._c_loadPluginLanguageFiles_2(C:\ckbuilder\src/lib/lang.js:26)
        at ckbuilder.lib.lang.call(C:\ckbuilder\src/lib/lang.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at ckbuilder.lib.lang._c_anonymous_5(C:\ckbuilder\src/lib/lang.js:104)
        at ckbuilder.lib.lang.call(C:\ckbuilder\src/lib/lang.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.builder._c_anonymous_20(C:\ckbuilder\src/lib/builder.js:700)
        at ckbuilder.lib.builder.call(C:\ckbuilder\src/lib/builder.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
        at ckbuilder.lib.controller._c_anonymous_5(C:\ckbuilder\src/lib/controller.js:78)
        at ckbuilder.lib.controller.call(C:\ckbuilder\src/lib/controller.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.controller._c_anonymous_14(C:\ckbuilder\src/lib/controller.js:235)
        at ckbuilder.lib.controller.call(C:\ckbuilder\src/lib/controller.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at ckbuilder.ckbuilder._c_script_0(C:\ckbuilder\src/ckbuilder.js:112)
        at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
        at ckbuilder.ckbuilder.exec(C:\ckbuilder\src/ckbuilder.js)
        at org.mozilla.javascript.optimizer.OptRuntime$1.run(OptRuntime.java:218)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.optimizer.OptRuntime.main(OptRuntime.java:206)
        at ckbuilder.ckbuilder.main(C:\ckbuilder\src/ckbuilder.js)
```
i`m build it under debian 9

UPD:
Sorry, it seems like plugin error. there is .php files instad .js

**Comment by jacekbogdanski** [comment]
Hello,

I checked and build tool works fine.

As you can see in an error message there is a problem with missing lang file inside `imageuploader` plugin: `/plugins/imageuploader/lang/en.js`. This is a third party plugin not maintained by the CKEditor team.

Please contact with plugin's author to report the problem. You'll always find plugin's contact details on it's [addon repository page](https://ckeditor.com/cke4/addon/imageuploader).
