### ISSUE TITLE
Build script fails on stable (OSX 10.12.6, Java 1.6.0_65)

### ISSUE THREAD

**Issue by deevolutionism** [ckeditor/ckeditor-dev#1831]
## Are you reporting a feature request or a bug?
Help
## Provide detailed reproduction steps (if any)
I attempted to build from the ckeditor-dev stable branch by running the build.sh script, but it failed with the following error:
```bash
./build.sh: line 1: ﻿#!/bin/bash: No such file or directory
CKBuilder - Builds a release version of ckeditor-dev.

Checking/Updating CKBuilder...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

Starting CKBuilder...
Exception in thread "main" org.mozilla.javascript.EvaluatorException: Function importClass must be called with a class; had "[JavaPackage com.google.javascript.jscomp.CompilationLevel]" instead. (C:\ckbuilder\src/lib/javascript.js#12)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:913)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:969)
	at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:932)
	at org.mozilla.javascript.ImporterTopLevel.js_importClass(ImporterTopLevel.java:162)
	at org.mozilla.javascript.ImporterTopLevel.execIdCall(ImporterTopLevel.java:237)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at ckbuilder.lib.javascript._c_script_0(C:\ckbuilder\src/lib/javascript.js:12)
	at ckbuilder.lib.javascript.call(C:\ckbuilder\src/lib/javascript.js)
	at ckbuilder.lib.javascript.exec(C:\ckbuilder\src/lib/javascript.js)
	at org.mozilla.javascript.tools.shell.Global.loadClass(Global.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at ckbuilder.ckbuilder._c_anonymous_3(C:\ckbuilder\src/ckbuilder.js:61)
	at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at ckbuilder.ckbuilder._c_script_0(C:\ckbuilder\src/ckbuilder.js:101)
	at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
	at ckbuilder.ckbuilder.exec(C:\ckbuilder\src/ckbuilder.js)
	at org.mozilla.javascript.optimizer.OptRuntime$1.run(OptRuntime.java:218)
	at org.mozilla.javascript.Context.call(Context.java:489)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
	at org.mozilla.javascript.optimizer.OptRuntime.main(OptRuntime.java:206)
	at ckbuilder.ckbuilder.main(C:\ckbuilder\src/ckbuilder.js)
```

## My system
os: macosx high sierra 10.12.6
java version "1.6.0_65"

**Comment by deevolutionism** [comment]
Silly me... Just need to download latest JDK.
[http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html](url)
