### ISSUE TITLE
Removing autocomplete inserted match characters with enabled throttling throws an error

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2194]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Use build editor
2. Open test: http://tests.ckeditor.test:1410/tests/plugins/autocomplete/manual/throttle
3. Open console
4. Insert autocomplete name
5. Wait moment and start to remove characters with backspace

### Expected result

no errors in console

### Actual result

there appears errors in console;

> Uncaught DOMException: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than the node's length (1).
>     at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.getClientRects (http://tests.ckeditor.test:1410/apps/ckeditor/ckeditor.js:187:3)
>     at getViewPosition (http://tests.ckeditor.test:1410/apps/ckeditor/plugins/autocomplete/plugin.js?t=I629:14:470)
>     at g.updatePosition (http://tests.ckeditor.test:1410/apps/ckeditor/plugins/autocomplete/plugin.js?t=I629:18:76)
>     at f.viewRepositionListener (http://tests.ckeditor.test:1410/apps/ckeditor/plugins/autocomplete/plugin.js?t=I629:11:217)
>     at f.<anonymous> (http://tests.ckeditor.test:1410/apps/ckeditor/plugins/autocomplete/plugin.js?t=I629:9:107)
>     at a.h (http://tests.ckeditor.test:1410/apps/ckeditor/ckeditor.js:10:70)
>     at a.<anonymous> (http://tests.ckeditor.test:1410/apps/ckeditor/ckeditor.js:11:433)
>     at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (http://tests.ckeditor.test:1410/apps/ckeditor/ckeditor.js:13:97)
>     at CKEDITOR.plugins.undo.UndoManager.type (http://tests.ckeditor.test:1410/apps/ckeditor/ckeditor.js:1195:102)
>     at CKEDITOR.plugins.undo.NativeEditingHandler.onKeyup (http://tests.ckeditor.test:1410/apps/ckeditor/ckeditor.js:1205:439)
> 

## Other details

* Browser: Opera
* OS: MacOS
* CKEditor version: 4.10.0
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Just note, in case it is just related to some timeout in the test - there's no reason to fix it, as it's just a test and doesn't bring any value to CKEditor itself.

**Comment by jacekbogdanski** [comment]
It looks like there is a problem with synchronization between editor#change event and autocomplete text watching. Editor change event uses range from the model, although this range is only updated during successful text match. With throttling, there is a delay between two events and change event executes view repositioning with out of data model range.

Because it's not an issue with the test but autocomplete bug, I will update the issue title and labels accordingly.

**Comment by Comandeer** [comment]
The issues seems to be no longer reproducible on `major` branch.

**Comment by engineering-this** [comment]
I can reproduce this issue.
1. Open: `tests/plugins/mentions/manual/mentions`.
2. Open console.
3. Focus editor and type: `@thomas`.
4. Keep quickly tapping backspace until you remove whole mention.

**Comment by mlewand** [comment]
I can confirm, I'm able to repro the issue too **on a built version**.  With dev version I did not reproduce it.

**Comment by MarianaPyrih** [comment]
Hi, we also constantly are getting this error. Has somebody any updates when it's going to be fixed?

**Comment by jbalinski** [comment]
Is this something the will be addressed any time soon?

**Comment by f1ames** [comment]
@MarianaPyrih @jbalinski I have added it to a current milestone (no ETA at the moment, but definitely this year) and we will try to work on this one.

**Comment by f1ames** [comment]
Confirmed for latest `master` that error still occurs (according to steps from https://github.com/ckeditor/ckeditor4/issues/2194#issuecomment-435906232) on built version. On dev version there is also an error in the console but slightly different:

```
plugin.js:229 Uncaught TypeError: Cannot read property 'element' of null
    at Object.CKEDITOR.plugins.textMatch.getRangeInText (plugin.js:229)
    at Object.CKEDITOR.plugins.textMatch.match (plugin.js:90)
    at TextWatcher.callback (plugin.js:168)
    at TextWatcher.testTextMatch (plugin.js:174)
    at TextWatcher.<anonymous> (tools.js:742)
    at ThrottleBuffer._call (tools.js:2691)
    at triggerOutput (tools.js:2565)
```

Tested with Chrome 78 on Linux Mint 19.2.

**Comment by jbalinski** [comment]
Is there still a chance that this will be addressed this year or is it being bumped?
