### ISSUE TITLE
Toggling styles with text selection inside table cell doesn't work correctly

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2419]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open console.
1. Open https://ckeditor.com/latest/samples/
1. Add table.
1. Type `foo` inside a table cell.
4. Select typed text (text selection, not table selection).
5. Press `Bold` button multiple times.

### Expected result

* No errors inside console.
* Bold toggles correctly.

### Actual result

* Bold doesn't remove style.
* Error inside console:
```
ckeditor.js:452 Uncaught DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 1.
    at CKEDITOR.dom.selection.selectRanges (https://ckeditor.com/latest/ckeditor.js:452:179)
    at CKEDITOR.style.y (https://ckeditor.com/latest/ckeditor.js:476:243)
    at CKEDITOR.style.remove (https://ckeditor.com/latest/ckeditor.js:479:261)
    at a.removeStyle (https://ckeditor.com/latest/ckeditor.js:487:355)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.command.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.styleCommand.exec (https://ckeditor.com/latest/ckeditor.js:486:155)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.command.exec (https://ckeditor.com/latest/ckeditor.js:200:395)
    at a.execCommand (https://ckeditor.com/latest/ckeditor.js:268:448)
    at CKEDITOR.ui.button.CKEDITOR.tools.extend.click (https://ckeditor.com/latest/ckeditor.js:650:419)
    at Object.execute (https://ckeditor.com/latest/ckeditor.js:651:497)
    at https://ckeditor.com/latest/ckeditor.js:652:369
```

## Other details

* CKEditor version: 4.10.1
* Installed CKEditor plugins: table, tableselection, basicstyles

**Comment by jacekbogdanski** [comment]
Duplicate of #941
