### ISSUE TITLE
CKEditor 4 Testing is broken

### ISSUE THREAD

**Issue by deti** [ckeditor/ckeditor-dev#3105]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
I'm following dev test instruction https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html

1. `npm install -g benderjs-cli`
2. `git clone https://github.com/ckeditor/ckeditor-dev.git`
3. `cd ckeditor-dev`
3. `npm install`
3. `bender init`
3. `bender server run`

### Expected result

Test serve starts ok

### Actual result

Script is broken and results in following exception

```bash
bender server run
info: [plugins] Loaded plugin: benderjs-coverage
info: [plugins] Loaded plugin: benderjs-yui
info: [plugins] Loaded plugin: benderjs-sinon
info: [plugins] Loaded plugin: benderjs-jquery
info: [plugins] Loaded plugin: tests/_benderjs/ckeditor
info: [plugins] Loaded plugin: benderjs-yui-beautified
internal/streams/legacy.js:28
  dest.on('drain', ondrain);
       ^

TypeError: dest.on is not a function
    at Request.Stream.pipe (internal/streams/legacy.js:28:8)
    at Request.pipe (~/ckeditor-dev/node_modules/benderjs-jquery/node_modules/request/request.js:1367:34)
    at next (~/ckeditor-dev/node_modules/benderjs-jquery/lib/index.js:109:8)
    at ~/ckeditor-dev/node_modules/benderjs-jquery/lib/index.js:121:5
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
```

## Other details
I was able to reproduce ☝️  on both my systems

* osX
  * node: v11.13.0
  * npm: 6.7.0
* Arch Linux
  * node: v11.14.0
  * npm: 6.9.0

**Comment by kylegibson** [comment]
For what it's worth, it worked for me:

```
~/dev/ckeditor-dev major*
❯ ~/.npm-packages/bin/bender init
info: Created Bender configuration files

~/dev/ckeditor-dev major*
❯ ~/.npm-packages/bin/bender server run
info: [plugins] Loaded plugin: benderjs-coverage
info: [plugins] Loaded plugin: benderjs-yui
info: [plugins] Loaded plugin: benderjs-sinon
info: [plugins] Loaded plugin: benderjs-jquery
info: [plugins] Loaded plugin: tests/_benderjs/ckeditor
info: [plugins] Loaded plugin: benderjs-yui-beautified
info: [jquery] Downloaded jquery-1.8.3.js
info: [jquery] Downloaded jquery-1.8.3.min.js
info: [jquery] Downloaded jquery-1.8.3.min.map
info: [jquery] Downloaded jquery-1.11.1.js
info: [jquery] Downloaded jquery-1.11.1.min.js
info: [jquery] Downloaded jquery-1.11.1.min.map
info: [jquery] Downloaded jquery-2.1.1.js
info: [jquery] Downloaded jquery-2.1.1.min.js
info: [jquery] Downloaded jquery-2.1.1.min.map
info: Bender.js v0.4.3 Server started at http://localhost:1030

info: Dashboard connected: /dashboard#n9sJm20mrY9HynQwAAAB
```

(I opened up http://localhost:1030 and all tests passed)

npm: 6.4.1
nodejs: v8.16.0

**Comment by jacekbogdanski** [comment]
I have no issue with testing environment following instruction steps, using NodeJS 10.15.0. I recommend using the LTS version which should be much more stable with benderjs than the latest one.

Please let us know if you still have the issue with NodeJS 10.15.0 so we can reopen this ticket.

**Comment by deti** [comment]
I confirm benderjs works fine on the latest LTS **10.15.3**.
