### ISSUE TITLE
Editor crashes after styling the cell with native selection

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#941]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Create new table.
2. Type something at some cell.
3. Select the word from step 2 (selection should be native).
4. Bold.
5. Unbold. 

### Expected result
The word has been unbolded. 

### Actual result
Editor crashes.

### Error
```
ckeditor.js:443 Uncaught DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 1.
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.selection.selectRanges (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:443:179)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.style.x (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:467:196)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.style.remove (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:470:261)
    at a.removeStyle (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:478:355)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.command.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.styleCommand.exec (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:477:155)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.command.exec (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:192:379)
    at a.execCommand (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:260:171)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.ui.button.CKEDITOR.tools.extend.click (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:640:419)
    at Object.execute (http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:641:490)
    at http://nightly.ckeditor.com/17-09-20-06-04/full/ckeditor.js:642:326
```

### GIF
![bug_cke4](https://user-images.githubusercontent.com/20988892/30633604-8d6b7ad2-9dec-11e7-8680-38af2847a417.gif)

## Other details
* Browser: All browsers
* OS: Windows 10, MacOS X
* CKEditor version: 4.7.3

**Comment by msamsel** [comment]
I just add `status:confirmed` to the issue, to be filtered out properly.

**Comment by HGSFB** [comment]
any updates on this?? i am facing the same issue

**Comment by mlewand** [comment]
Not yet, adding to the backlog.
